#+Title: A CiSE Department Contribution on Org-mode
#+Author:
#+Options: ^:nil toc:nil

Guidelines:
- http://www.computer.org/portal/web/peerreviewmagazines/accise
- http://www.computer.org/portal/web/peerreviewmagazines/dgcise

The actual article will live in file:org-mode-active-doc.org (name of
file and subject obviously subject to change).  This document can be
used for project management.

* Tasks [1/4]
** TODO Department Guidelines
http://www.computer.org/portal/web/peerreviewmagazines/dgcise

- must be roughly 3000 words, less 250 for every figure
  #+begin_src sh
    pdftotext org-mode-active-doc.pdf - |wc -w
  #+end_src

  #+results:
  : 1409

** DONE apply the CiSE template
no specific template required

** TODO CiSE Deadline
   DEADLINE: <2011-02-22 Tue>

** TODO Figure out a motivating example
Topic
#+begin_quote Konrad
  That means stuff such as simple numerical algorithms, basic
  statistics, fitting curves.
#+end_quote

*** Languages/Tools -- some subset of the following
- gnuplot
- R
- Python
- shell

*** Features
- code blocks in multiple languages, passing data between blocks
- flow of data to/from an external resource either a live data
  repository available on the web, an external file or database,
  etc...
- generation of a figure
- possibly interaction with data stored in a table in the document

*** Online Data options (baseball)
After much thrashing with non-text formatted data from the many links
below, I've settled on doing a baseball example with the nicely
formatted text files from http://www.retrosheet.org/.

- http://archive.stsci.edu/fuse/retrieval_help.html -- FUSE project
  data, spectral data from a variety of astronomical targets -- this
  looks like the way to go, hopefully no too difficult to put together
  a simple star spectroscopy example from this data.
- http://archive.stsci.edu/ -- sky data
- http://infochimps.com/tags/Science -- Suggested by Konrad
- http://www.data.gov/catalog/raw
- http://cas.sdss.org/dr6/en/ -- data from map of the sky
  - [[http://www.sdss.org/dr6/dm/flatFiles/FILES.html][data release 6]]
- [[http://ed.fnal.gov/samplers/hsphys/activities/summary.shtml][educational example]] -- quark mass calculation
